name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Rust toolchain
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - name: Build
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo build --release
    - name: Run clippy
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo clippy --release
    - name: Run test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo test --release
    - name: Publish test
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo publish --dry-run
    - name: Install zine and build demo
      run: |
        export PATH="$HOME/.cargo/bin:$PATH"
        cargo install --path .
        # Test build demo
        cd demo; zine build
        # Test new empty project then build
        zine new test; cd test; zine build
    - uses: actions/upload-artifact@v3
      with:
        name: zine
        path: ./target/release/zine
